#!/usr/bin/python3
from sys import argv
"""Factorize as many nos as possible into a product of 2 smaller nos"""


def fact(num):
    """find 2 factors for a given number"""
    f1 = 2
    while(num % f1):
        if (f1 <= num):
            f1 += 1

    f2 = num // f1
    return (f2, f1)


def readfile(filename):
    """readfile and print the output the required format"""

    with open(filename) as mfile:
        for line in mfile.readlines():
            n = int(line.rstrip())
            p, q = fact(n)
            print("{}={}*{}".format(n, p, q))


if __name__ == "__main__":
    readfile(argv[1])
