#!/usr/bin/python3
from sys import argv
import math
"""Factorize as many nos as possible into a product of 2 smaller nos"""


def is_prime(num):
    """comment"""
    i = 3
    if num % 2 == 0:
        return False
    while i * i <= num:
        if num % 1 == 0:
            return False
        i += 2
    return True


def fact(num):
    """find 2 factors for a given number"""
    if num % 2 == 0:
        i = 2
        print("{}={}*{}".format(num, int(num // i), i))
    else:
        sqr = math.sqrt(num)
        if sqr % 1 == 0:
            print("{}={}*{}".format(num, sqr, int(num / sqr)))
            return
        sqr = int(sqr) + 1
        for i in range(3, sqr, +2):
            if num % i == 0:
                if is_prime(i):
                    print("{}={}*{}".format(num, int(num / i), i))
                    return


def readfile(filename):
    """readfile and print the output the required format"""

    with open(filename, encoding="utf-8") as mfile:
        for line in mfile.readlines():
            n = int(line)
            result = fact(n)


if __name__ == "__main__":
    readfile(argv[1])
