#!/usr/bin/python3
from sys import argv
import math
"""Factorize as many nos as possible into a product of 2 smaller nos"""


def fact(num):
    """find 2 factors for a given number"""
    if num % 2 == 0:
        i = 2
        print("{}={}*{}".format(num, int(num // i), i))
    else:
        sqr = int(math.sqrt(num)) + 1
        for i in range(3, sqr, +2):
            if num % i == 0:
                print("{}={}*{}".format(num, int(num // i), i))
                return
            if num % (sqr + i) == 0:
                print("{}={}*{}".format(num, sqr + i, int(num // (sqr + i))))
                return
            if num % (sqr - i) == 0:
                print("{}={}*{}".format(num, sqr - i, int(num // (sqr - i))))
                return


def readfile(filename):
    """readfile and print the output the required format"""

    with open(filename, encoding="utf-8") as mfile:
        for line in mfile.readlines():
            n = int(line)
            result = fact(n)


if __name__ == "__main__":
    readfile(argv[1])
